version: '3.7'

services:
  app:
    build:
      context: .
    depends_on:
      - redis
    ports:
      - '8000:8000'
    environment:
      - REDIS_URL=redis://redis

  redis:
    image: 'redis:6'